name = "modularity"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Modularity"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "main"

[[lean_lib]]
name = "Modularity"
