import Canonical
import Lean.Elab.Tactic
import Mathlib.Data.Int.Basic
import Mathlib.Data.List.Basic
import Mathlib.Algebra.Ring.Basic
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Linarith
import Mathlib.Data.ZMod.Basic

universe u v w
variable {α β: Type}
variable {f m: Type → Type}


-- # Effects in Lean

-- We want to replicate the following Haskell effects in Lean
-- https://casperbp.net/posts/2023-07-algebraic-effects/

-- ## Free monads

-- The free monad generated by a signture is the type of programs or syntax trees
-- where the operations are given by the constructors of the signature.

-- To understand monads and lawful monads in Lean, see
-- https://lean-lang.org/functional_programming_in_lean/Functors___-Applicative-Functors___-and-Monads/

-- The implementation of free monads in Lean is based on
-- https://leanprover-community.github.io/archive/stream/270676-lean4/topic/Free.20monad.html

class FreeMonad (f : Type u → Type v) (m : Type w → Type u) extends Monad m where
  is_free : (a : Type w) → f (m a) → m a

def FreeM (f : Type u → Type v) (α : Type u) : Type _ :=
  ((m : Type u → Type u) → [FreeMonad f m] → [LawfulMonad m] → m α)

def FreeM.pure (x : α) : FreeM f α :=
  fun _ _ => Pure.pure x

def FreeM.bind (x : FreeM f α) (g : α → FreeM f β) : FreeM f β :=
  fun m _ => x m >>= (g · m)

instance [Monad m] : FreeMonad m m where
  is_free _ := (· >>= id)

def FreeM.run [Monad m] [LawfulMonad m] (f : FreeM m α) : m α := f m

instance : Monad (FreeM f) where
  pure := FreeM.pure
  bind := FreeM.bind

macro "simp_funext" : tactic => `(tactic|
  funext m <;>
  funext <;>
  simp [Functor.map, FreeM.bind, FreeM.pure, Seq.seq,
        SeqLeft.seqLeft, SeqRight.seqRight, pure, bind] <;>
  try rfl)

instance : LawfulMonad (FreeM f) where
  map_const := rfl
  id_map x := by simp_funext
  comp_map g h x := by simp_funext
  seqLeft_eq x y := by simp_funext
  seqRight_eq x y := by simp_funext
  pure_seq g x := by simp_funext
  bind_pure_comp f x := by simp_funext
  bind_map f x := by simp_funext
  pure_bind x f := by simp_funext
  bind_assoc x f g := by simp_funext

-- ## State Monads

-- See Lean's implementation of the state monad
-- https://lean-lang.org/doc/reference/latest//Functors___-Monads-and--do--Notation/Varieties-of-Monads/#state-monads




-- References
-- https://lean-lang.org/functional_programming_in_lean/
